---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: true
  sudo: true
  sudo_user: admin

  tasks:
  - name: Pull sources from the repository.
    git: repo={{ project_repo }} dest={{ project_root }}/code/ version={{ branch }}
    when: vm == 0
    notify:
      - restart info-hub

  handlers:
    - include: handlers.yml
